### ISSUE TITLE
Unable to start Neo4j. java.lang.NumberFormatException: null

### ISSUE THREAD

**Issue by willmoss** [thallium205/BitcoinVisualizer#15]
Hi,

I'm trying to run visualizer on Windows 7

I installed Neo4j Enterprise 1.8.3 and Java 6 (for backwards compatibility) 

I started the server Neo4jCoordinator.bat

I run BlockViewer.jar with the following command

Y:\Documents\bitcoin\BitcoinVisualizer\server\jar>java -jar -Xmx512m BlockViewer
.jar -dbPath Y:\Documents\bitcoin\neo4j-enterprise-1.8.3\data\graph.db\ -configP
ath Y:\Documents\bitcoin\neo4j-enterprise-1.8.3\conf\neo4j.properties -validate
false -client

I'm getting the following error:

Aug 22, 2013 5:21:45 PM bitcoinvisualizer.Main main
SEVERE: Unable to start Neo4j.
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.valueOf(Unknown Source)
        at org.neo4j.graphdb.factory.GraphDatabaseSetting$IntegerSetting.valueOf
(GraphDatabaseSetting.java:212)
        at org.neo4j.graphdb.factory.GraphDatabaseSetting$IntegerSetting.valueOf
(GraphDatabaseSetting.java:176)
        at org.neo4j.kernel.configuration.Config.get(Config.java:113)
        at org.neo4j.kernel.HighlyAvailableGraphDatabase.<init>(HighlyAvailableG
raphDatabase.java:259)
        at org.neo4j.kernel.HighlyAvailableGraphDatabase.<init>(HighlyAvailableG
raphDatabase.java:209)
        at bitcoinvisualizer.Main.main(Main.java:62)
Aug 22, 2013 5:21:45 PM bitcoinvisualizer.GraphBuilder StartDatabase
INFO: Starting database...
Exception in thread "main" java.lang.NullPointerException
        at bitcoinvisualizer.GraphBuilder.StartDatabase(GraphBuilder.java:146)
        at bitcoinvisualizer.Main.main(Main.java:94)

I took a look at the code, there seems to be some issue with the class `HighlyAvailableGraphDatabase` when initializing Neo4j. Unfortunately there is not a lot information around on the net about this class - it seems it may have been superseeded in Neo4j 1.9

I tried this on Windows & Linux, and got the same error.

Without a fix for this, the program is kinda unusable.

Cheers!

**Comment by huangzhong** [comment]
Hi Willmoss, did you fix the problem?
